# Netlify Configuration File

[build]
  command = "npm run dev"
  functions = "netlify/functions"
  publish = ".next"

# ✅ Enable Netlify Next.js Plugin for better compatibility
[[plugins]]
  package = "@netlify/plugin-nextjs"

# ✅ Increase Netlify Function timeout for long-running API calls
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]
  included_files = ["src/**/*.ts", "src/**/*.js"]
  timeout = 30  # Increase function timeout to 30 seconds

# ✅ Redirect API requests to your backend
[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = true
